name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '11 1 * * 0'


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # We need to avoid using NodeJS v20, because it doesn't work with
      # older glibc versions.  See:
      #  https://github.com/actions/checkout/issues/1809.
      #ACTIONS_RUNNER_FORCED_INTERNAL_NODE_VERSION: node16
      #ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION: node16
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    strategy:
      matrix:
        compiler:
          - clang
          - gcc
        container:                    
          - ubuntu:22.04

    container: ${{ matrix.container }}

    steps:
      - name: Checkout ProFTPD
        uses: actions/checkout@v3
        with:
          repository: proftpd/proftpd
          path: proftpd

      - name: Checkout module source code
        uses: actions/checkout@v3
        with:
          path: proftpd/contrib/mod_prometheus

      - name: Whitespace check
        if: ${{ matrix.container == 'ubuntu:22.04' }}
        run: |
          apt-get update -qq
          apt-get install -y git
          cd proftpd/contrib/mod_prometheus
          pwd
          ls -al
          git status
          if [ -n $(git diff --check HEAD^) ]; then
            echo "You must remove whitespace before submitting a pull request"
            echo ""
            git diff --check HEAD^
            exit 1
          fi

      - name: Install Ubuntu packages
        if: ${{ matrix.container == 'ubuntu:22.04' }}
        run: |
          apt-get update -qq
          # for builds
          apt-get install -y clang gcc make
          # for unit tests
          apt-get install -y check libsubunit-dev

          # for libmicrohttpd support
          apt-get install -y libmicrohttpd-dev
          # for SQLite support
          apt-get install -y libsqlite3-dev sqlite3
          # for OpenSSL support
          apt-get install -y libssl-dev
          # for zlib support
          apt-get install -y zlib1g-dev

          # for integration/regression test
          apt-get install -y \
            libcompress-raw-zlib-perl \
            libdata-dumper-simple-perl \
            libdatetime-perl \
            libfile-copy-recursive-perl \
            libfile-path-tiny-perl \
            libfile-spec-native-perl \
            libnet-inet6glue-perl \
            libnet-ssh2-perl \
            libnet-ssleay-perl \
            libnet-telnet-perl \
            libposix-2008-perl \
            libtest-unit-perl \
            libtime-hr-perl \
            libwww-perl
          PERL_MM_USE_DEFAULT=1 perl -MCPAN -e 'install Net::FTPSSL'

          # for test code coverage
          apt-get install -y lcov ruby
          gem install coveralls-lcov
          # for HTML validation
          apt-get install -y tidy
          # for debugging
          clang --version
          gcc --version
          openssl version -a

      - name: Build as shared module
        env:
          CC: ${{ matrix.compiler }}
        run: |
          cd proftpd
          make clean
          ./configure LIBS="-lm -lsubunit -lrt -pthread" --enable-devel --enable-dso --with-shared=mod_prometheus
          make

      - name: Install as shared module
        run: |
          cd proftpd
          make install

      - name: Check HTML docs
        if: ${{ matrix.container == 'ubuntu:22.04' }}
        run: |
          cd proftpd/contrib/mod_prometheus
          for f in $(/bin/ls *.html); do echo "Processing $f"; tidy -errors -omit -q $f; done || exit 0
